### ISSUE TITLE
Fix error on for loop

### ISSUE THREAD

**Issue by afnizarnur** [afnizarnur/herohr-app#5]
<img width="912" alt="screen shot 2017-05-05 at 1 00 41 am" src="https://cloud.githubusercontent.com/assets/4648648/25717924/560ce092-312e-11e7-988f-d819ec95c31c.png">

Error pada looping, seharusnya memunculkan 2 lowongan kerja, tolong @aldikawicaksono006 fix error ini

**Comment by aldikawicaksono006** [comment]
Sudah
